# Generated by Django 3.2.7 on 2021-09-24 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(max_length=250),
        ),
    ]
